export const employeesArray = [
  {
    empName: "John",
    compName: "ABC Corp",
    role: ["Front End Dev"],
    techStack: ["React"],
    experience: 5,
    availability: "yes",
    gender: "male",
    resume: {
      fileType: "pdf",
      fileLinks: "https://example.com/john_resume.pdf",
    },
    id: Date.now().toLocaleString(),
  },
  {
    empName: "Jane",
    compName: "XYZ Inc",
    role: ["Front End Dev"],
    techStack: ["Angular"],
    experience: 3,
    availability: "yes",
    gender: "female",
    resume: {
      fileType: "docx",
      fileLinks: "https://example.com/jane_resume.docx",
    },
    id: Date.now().toLocaleString(),
  },
  {
    empName: "Alex",
    compName: "123 Tech",
    role: ["Front End Dev"],
    techStack: ["React"],
    experience: 7,
    availability: "no",
    gender: "male",
    resume: {
      fileType: "pdf",
      fileLinks: "https://example.com/alex_resume.pdf",
    },
    id: Date.now().toLocaleString(),
  },
  {
    empName: "Mia",
    compName: "Top Solutions",
    role: ["Front End Dev"],
    techStack: ["Angular"],
    experience: 2,
    availability: "no",
    gender: "female",
    resume: {
      fileType: "pdf",
      fileLinks: "https://example.com/mia_resume.pdf",
    },
    id: Date.now().toLocaleString(),
  },
  {
    empName: "Chris",
    compName: "Innovate Co",
    role: ["Front End Dev"],
    techStack: ["React"],
    experience: 4,
    availability: "yes",
    gender: "male",
    resume: {
      fileType: "pdf",
      fileLinks: "https://example.com/chris_resume.pdf",
    },
    id: Date.now().toLocaleString(),
  },
  {
    empName: "Olivia",
    compName: "Global Software",
    role: ["Front End Dev"],
    techStack: ["Angular"],
    experience: 6,
    availability: "yes",
    gender: "female",
    resume: {
      fileType: "pdf",
      fileLinks: "https://example.com/olivia_resume.pdf",
    },
    id: Date.now().toLocaleString(),
  },
  {
    empName: "Michael",
    compName: "ABC Corp",
    role: ["Front End Dev"],
    techStack: ["React"],
    experience: 8,
    availability: "no",
    gender: "male",
    resume: {
      fileType: "pdf",
      fileLinks: "https://example.com/michael_resume.pdf",
    },
    id: Date.now().toLocaleString(),
  },
  {
    empName: "Emily",
    compName: "XYZ Inc",
    role: ["Front End Dev"],
    techStack: ["Angular"],
    experience: 1,
    availability: "yes",
    gender: "female",
    resume: {
      fileType: "pdf",
      fileLinks: "https://example.com/emily_resume.pdf",
    },
    id: Date.now().toLocaleString(),
  },
  {
    empName: "Daniel",
    compName: "123 Tech",
    role: ["Front End Dev"],
    techStack: ["Angular"],
    experience: 9,
    availability: "yes",
    gender: "male",
    resume: {
      fileType: ["docx"],
      fileLinks: ["https://example.com/daniel_resume.docx"],
    },
    id: Date.now().toLocaleString(),
  },
  {
    empName: "Sophia",
    compName: "Top Solutions",
    role: ["Front End Dev"],
    techStack: ["React"],
    experience: 3,
    availability: "yes",
    gender: "female",
    resume: {
      fileType: ["pdf"],
      fileLinks: ["https://example.com/sophia_resume.pdf"],
    },
    id: Date.now().toLocaleString(),
  },
];

console.log(employeesArray);
